ServerEvents.recipes(event => {
    event.recipes.modular_machinery_reborn.machine_recipe("mind:die_casting_machine",600)
        .height(70)
        .width(120)
        .requireEnergy(500,0,0)
        .requireItem('2x immersiveengineering:plate_iron',22,18)
        .requireItem('2x ytech:iron_bolt',40,18)
        .requireItem('immersiveengineering:stick_iron',58,18)
        .progressX(78)
        .progressY(18)
        .produceItem('minecraft:bucket',103,18)
    event.recipes.modular_machinery_reborn.machine_recipe("mind:die_casting_machine",300)
        .height(70)
        .width(120)
        .requireEnergy(100,0,0)
        .requireItem('4x ytech:wooden_plate',22,9)
        .requireItem('2x minecraft:redstone',40,9)
        .requireItem('3x minecraft:cobblestone',58,9)
        .requireItem('minecraft:iron_ingot',40,27)
        .progressX(78)
        .progressY(18)
        .produceItem('minecraft:piston',103,18)
    event.recipes.modular_machinery_reborn.machine_recipe("mind:die_casting_machine",300)
        .height(70)
        .width(120)
        .requireEnergy(100,0,0)
        .requireItem('modular_machinery_reborn:casing_plain',40,9)
        .requireItem('4x pneumaticcraft:heat_sink',40,27)
        .progressX(78)
        .progressY(18)
        .produceItem('modular_machinery_reborn:casing_vent',103,18)
})      