ServerEvents.recipes(event => {
    event.recipes.modular_machinery_reborn.machine_recipe("mind:research_station",200)
        .requireItem('minecraft:soul_torch',0,0)
        .requireItem('naturesaura:clock_hand',18,0)
        .requireItem('4x advanced_ae:quantum_accelerator',36,0)
        .requireItem('advanced_ae:quantum_processor',0,18)
        .requireItem('megacells:accumulation_processor',18,18)
        .requireFluid("pneumaticcraft:plastic",36,18)
        .requireExperience(1024)
        .requireSource(32000,18,36)
        .produceItem("mind:torcherino_research_point",90,18)
        .width(130)
        .height(100)
        .progressX(61)
        .progressY(18)
})