#Base factor for working out machine performance with upgrades - UpgradeModifier * (UpgradesInstalled/UpgradesPossible).
# Default: 20
# Range: > 1
maxUpgradeMultiplier = 20

#Configurable Auto Inserter
[AutoInsert]
	#Configurable item rate for Auto Inserter
	# Default: 8
	# Range: 1 ~ 64
	itemRate = 8
	#Configurable chemical rate for Auto Inserter
	# Default: 128
	# Range: 1 ~ 9223372036854775807
	chemicalRate = 128
	#Configurable fluid rate for Auto Inserter
	# Default: 128
	# Range: > 1
	fluidRate = 128
	#Configurable energy rate for Auto Inserter
	# Default: 128
	# Range: 1 ~ 9223372036854775807
	energyRate = 128
