#setting for Extended Crafting Terminal
["Extended Crafting"]

	#Basic Terminal
	["Extended Crafting"."Basic Crafting Terminal"]
		#enable basic crafting terminal
		Enable = true
		#The AE system must be online and powered to perform the crafting.
		"Craftable when Active" = false
		#basic crafting terminal drain passive AE
		# Default: 1.0
		# Range: 0.0 ~ 1.7976931348623157E308
		"Passive drain AE" = 1.0

	#Advanced Terminal
	["Extended Crafting"."Advanced Crafting Terminal"]
		#enable advanced crafting terminal
		Enable = true
		#The AE system must be online and powered to perform the crafting.
		"Craftable when Active" = false
		#advanced crafting terminal drain passive AE
		# Default: 1.0
		# Range: 0.0 ~ 1.7976931348623157E308
		"Passive drain AE" = 1.0

	#Elite Terminal
	["Extended Crafting"."Elite Crafting Terminal"]
		#enable elite crafting terminal
		Enable = true
		#The AE system must be online and powered to perform the crafting.
		"Craftable when Active" = false
		#elite crafting terminal drain passive AE
		# Default: 1.0
		# Range: 0.0 ~ 1.7976931348623157E308
		"Passive drain AE" = 1.0

	#Ultimate Terminal
	["Extended Crafting"."Ultimate Crafting Terminal"]
		#enable ultimate crafting terminal
		Enable = true
		#The AE system must be online and powered to perform the crafting.
		"Craftable when Active" = false
		#ultimate crafting terminal drain passive AE
		# Default: 1.0
		# Range: 0.0 ~ 1.7976931348623157E308
		"Passive drain" = 1.0
