#Expand all entity hitboxes by 10%, making hitting a target possible from a slightly greater range and with much increased accuracy.
#Default Value: true
inflate_hitboxes = true
#Disable rendering for certain particle types from modern combat, since they kinda clutter the screen since attacks can be dealt much quicker with classic combat options enabled.
#This option can be used to prevent basically any particle from showing.
#Format for every entry is "<namespace>:<path>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. May use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*_shulker_box" to match all shulker boxes no matter of color. Begin an entry with "!" to make sure it is excluded, useful e.g. when it has already been matched by another pattern.
#Default Value: [minecraft:damage_indicator, minecraft:sweep_attack]
canceled_particles = ["minecraft:damage_indicator", "minecraft:sweep_attack"]
#Is the sweeping edge enchantment required to perform a sweep attack.
#Default Value: true
require_sweeping_edge = true
#Attacking will no longer stop the player from sprinting. Very useful when swimming, so you can fight underwater without being stopped on every hit.
#Default Value: true
sprint_attacks = true
#Sprinting and attacking no longer interfere with each other, making critical hits possible at all times.
#Default Value: true
critical_hits_while_sprinting = true
#Completely remove the attack cooldown as if it never even existed in the first place.
#Default Value: true
remove_attack_cooldown = true
#Makes knockback stronger towards targets not on the ground (does not apply when in water).
#Default Value: true
upwards_knockback = true
#Prevent various attack sounds added for the cooldown mechanic from playing.
#This option can be used to prevent basically any individual sound from playing.
#Format for every entry is "<namespace>:<path>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. May use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*_shulker_box" to match all shulker boxes no matter of color. Begin an entry with "!" to make sure it is excluded, useful e.g. when it has already been matched by another pattern.
#Default Value: [minecraft:entity.player.attack.crit, minecraft:entity.player.attack.knockback, minecraft:entity.player.attack.nodamage, minecraft:entity.player.attack.strong, minecraft:entity.player.attack.weak, minecraft:entity.player.attack.sweep]
canceled_attack_sounds = ["minecraft:entity.player.attack.crit", "minecraft:entity.player.attack.knockback", "minecraft:entity.player.attack.nodamage", "minecraft:entity.player.attack.strong", "minecraft:entity.player.attack.weak", "minecraft:entity.player.attack.sweep"]
#Allow using the "Attack" button while the "Use Item" button is held for mining blocks. Does not make a lot of sense, but it used to be a feature in old pvp.
#Default Value: false
interact_while_using = false
#Give Regeneration V and Absorption I instead of Regeneration II and Absorption IV after consuming a notch apple.
#Default Value: true
notch_apple_effects = true
#Health only regenerates every 4 seconds, while requiring 18 or more food points. Surplus saturation does not yield quick health regeneration.
#Default Value: false
legacy_food_mechanics = false
#Player is knocked back by attacks which do not cause any damage, such as when hit by snowballs, eggs, and fishing rod hooks.
#Default Value: true
weak_attacks_knock_back_players = true

[fishing_rods]
	#Hooking entities with a fishing rod causes only 3 damage points to the rod instead of 5.
	#Default Value: true
	slower_breaking = true
	#Fishing rod deals knockback upon hitting an entity.
	#Default Value: true
	cause_knockback = true
	#Entities reeled in using a fishing rod are slightly launched upwards.
	#Default Value: true
	launch_entities = true
