#Only damage tools by 1 durability instead of 2 when attacking. Apply the same logic to swords when harvesting blocks.
#Default Value: true
#Requires Restart: Game
no_item_durability_penalty = true
#Overrides for setting and balancing attack damage values of items.
#Takes precedence over any changes made by "legacy_attack_damage" option, but requires it to be enabled.
#As with all items, this value is added ON TOP of the default attack strength of the player (which is 1.0 by default).
#Format for every entry is "<namespace>:<path>,<amount>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. May use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*_shulker_box" to match all shulker boxes no matter of color.
#Default Value: []
#Requires Restart: Game
attack_damage_overrides = [""]
#Boost sharpness enchantment to 1.25 damage points per level instead of just 0.5.
#Default Value: false
#Requires Restart: Game
boost_sharpness = false
#Revert weapon and tool attack damage to legacy values.
#Default Value: true
#Requires Restart: Game
legacy_attack_damage_values = true
