[chemical_package_filler]
	#How much FE the Chemical Package Filler should hold.
	# Default: 5000
	# Range: > 0
	energy_capacity = 5000
	#How much total FE the Chemical Package Filler should use per operation.
	# Default: 500
	# Range: > 0
	energy_req = 500
	#How much FE/t maximum the Chemical Package Filler can use.
	# Default: 100
	# Range: > 0
	energy_usage = 100
