ServerEvents.recipes(event => {
    let { custommachinery } = event.recipes
    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 2400)
        .produceItem("3x draconicevolution:draconium_core", "output")
        .requireItem("4x extendedcrafting:crystaltine_nugget")
        .requireItem("#c:ingots/draconium")
        .requireItem("minecraft:dragon_breath")
        .requireChemical("10x mekanism:antimatter")
        .requireEnergyPerTick(1000)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:wither_skeleton_skull", "output")
        .requireItem("minecraft:skeleton_skull")
        .requireChemical("5x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:quartz_block", "output")
        .requireItem("minecraft:light_gray_wool")
        .requireChemical("2x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:heart_of_the_sea", "output")
        .requireItem("minecraft:nether_star")
        .requireChemical("5x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:redstone_block", "output")
        .requireItem("minecraft:red_wool")
        .requireChemical("2x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:end_crystal", "output")
        .requireItem("minecraft:beacon")
        .requireChemical("3x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:iron_ingot", "output")
        .requireItem("mekanism:ingot_tin")
        .requireChemical("3x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:respawn_anchor", "output")
        .requireItem("#minecraft:beds")
        .requireChemical("3x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:diamond", "output")
        .requireItem("minecraft:coal")
        .requireChemical("4x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:emerald", "output")
        .requireItem("minecraft:diamond")
        .requireChemical("4x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:enchanted_golden_apple", "output")
        .requireItem("minecraft:golden_apple")
        .requireChemical("3x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:chorus_flower", "output")
        .requireItem("#minecraft:flowers")
        .requireChemical("2x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:crying_obsidian", "output")
        .requireItem("minecraft:obsidian")
        .requireChemical("1x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:glowstone", "output")
        .requireItem("minecraft:yellow_wool")
        .requireChemical("2x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:crossbow", "output")
        .requireItem("minecraft:bow")
        .requireChemical("1x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:echo_shard", "output")
        .requireItem("minecraft:amethyst_shard")
        .requireChemical("2x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:trident", "output")
        .requireItem("minecraft:diamond_sword")
        .requireChemical("4x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:phantom_membrane", "output")
        .requireItem("#c:leathers")
        .requireChemical("3x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:dragon_egg", "output")
        .requireItem("minecraft:egg")
        .requireChemical("4x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:ender_chest", "output")
        .requireItem("#c:chests")
        .requireChemical("2x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("mekanism_extras:enriched_shining", "output")
        .requireItem("mekanism_extras:enriched_thermonuclear")
        .requireChemical("1x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:lapis_block", "output")
        .requireItem("minecraft:blue_wool")
        .requireChemical("2x mekanism:antimatter")
        .requireEnergyPerTick(100)

    custommachinery.custom_machine("custommachinery:antimatter_fusion_converter", 200)
        .produceItem("minecraft:nautilus_shell", "output")
        .requireItem("minecraft:flower_pot")
        .requireChemical("3x mekanism:antimatter")
        .requireEnergyPerTick(100)
})