ServerEvents.recipes(event => {
    let { custommachinery } = event.recipes
    custommachinery.custom_machine("custommachinery:precision_material_assembly_inst", 1200)
        .produceItem('stellaris:rocket_nose_cone')
        .requirePressure(15.0, 24.0)
        .requireSU(128, 2)
        .requireHeat(235.00)
        .requireItem('8x extendedcrafting:ender_ingot')
        .requireItem('8x megacells:sky_steel_ingot')
        .requireItem('10x mekanism:enriched_redstone')

    custommachinery.custom_machine("custommachinery:precision_material_assembly_inst", 1200)
        .produceItem('2x stellaris:rocket_fin')
        .requirePressure(15.0, 24.0)
        .requireSU(128, 2)
        .requireHeat(235.00)
        .requireItem('16x extendedcrafting:ender_ingot')
        .requireItem('16x megacells:sky_steel_ingot')
        .requireItem('3x mekanism:reprocessed_fissile_fragment')

    custommachinery.custom_machine("custommachinery:precision_material_assembly_inst", 1200)
        .produceItem('stellaris:rocket_engine')
        .requirePressure(15.0, 24.0)
        .requireSU(128, 2)
        .requireHeat(235.00)
        .requireItem('16x stellaris:heavy_metal_plate')
        .requireItem('16x megacells:sky_steel_ingot')
        .requireItem('16x ironjetpacks:thruster[ironjetpacks:jetpack_id="ironjetpacks:emerald"]')
})